language: node_js
node_js:
  - "10"
install:
  - npm install
stages:
  - "Quality gates"
  - "Build"
  - name: "Delivery"
    if: type != pull_request
        AND branch = master
jobs:
  include:
    - stage: "Quality gates"
      name: "Linter"
      script: npm run lint
    - script: npm test
      name: "Unit Tests"
    - stage: "Build"
      script: npm run build
    - stage: "Delivery"
      script: npm run deploy
branches:
  only:
    - master
addons:
  ssh_known_hosts:
  - 68.183.2.140
